apiVersion: v1
kind: Secret
metadata:
  name: cnsecret
  labels:
    training: cn2
stringData:
  apikey: "c7e9de1e93637eb6157e3ab03698169e0fe392b17204dc42c12c2c55aa607819"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appb
  labels:
    app: appb
    training: cn2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appb
      training: cn2
  template:
    metadata:
      labels:
        app: appb
        training: cn2
    spec:
      containers:
      - name: app
        image: quay.io/drsylent/cubix/block7v2/homework:springboot3native
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: cnsecret
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 8081
          name: management
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: appb
  labels:
    app: appb
    training: cn2
spec:
  selector:
    app: appb
    training: cn2
  ports:
    - name: web
      port: 8080
      targetPort: web
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: appb
  labels:
    app: appb
    training: cn2
    release: prometheus-operator
spec:
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: appb
      training: cn2
